services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./backend/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - app-network
    ports:
      - "8000:8000"
    environment:
      DB_HOST: laravel_db
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root

  db:
    image: mysql:5.7
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3307:3306"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
